baseURL: "https://asmagnets.com"
languageCode: en-us
title: AsMagnets
theme: PaperMod

params:
  defaultTheme: light
  disableThemeToggle: true

  homeInfoParams:
      Title: AsMagnets - Reputation Marketing Consultant
      Content: AsMagnets is a reputation marketing consulting company that specializes in building and promoting a positive image for businesses. Our team of experts understands the importance of reputation in today's digital age and works tirelessly to ensure our clients are seen in the best light possible. From crafting compelling brand narratives to managing online reviews, we offer a range of services to enhance your reputation and attract more customers. Our goal is to help businesses like yours stand out in a crowded marketplace and build a loyal customer base. With AsMagnets, you can expect results-driven strategies and a commitment to your success..
      
  socialIcons:
  Name: facebook
  Url: “https://facebook.com/”
  Name: twitter
  Url: “https://twitter.com/”

  cover: 
      linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true




menu: 
  main: 
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
      
    - identifier: services
      name: Services
      url: /services/
      weight: 20

    - identifier: contact
      name: Contact
      url: /contact
      weight: 60

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false